channels:
- conda-forge
dependencies:
- python >=3.10,<3.12
- aimsgb =0.1.3
- ipycanvas =0.13.2
- ipython =8.24.0
- ipywidgets =7.7.1
- jupyterlab =3.6.7
- matplotlib =3.8.4
- nglview =3.0.8
- numpy =1.26.4
- openjdk =22.0.1
- owlready2 =0.46
- pandas =1.5.3
- pyiron-data =0.0.27
- pyiron_atomistics = 0.5.4
- pyiron_base =0.5.33
- pyiron_gui =0.0.8
- pyiron_ontology =0.1.3
- pymatgen =2023.5.10
- ryvencore =0.3.1.1
- seaborn =0.13.2
- traitlets =5.14.3
